// lyrics of the portal credits song - still alive.
// this is one to one copy of the original time data at https://github.com/errorer/Portal_StillAlive_Python
// also, the credits section is omitted here, as it's not needed

export interface LyricLine {
    words: string | number; // The lyric line to display. if its a number then its ascii art index
    time: number; // Time in centiseconds when this line should appear
    interval: number; // Duration to display the line (optional)
    mode: 'LYRIC_NEWLINE' | 'START_MUSIC' | 'DRAW_ART' | 'CLEAR_LYRICS' | 'LYRIC_NONEWLINE' | 'END'; // Mode of the line
}

// A direct translation of the data structure
// i like to think of this copying the timeline from a premiere pro project
export const timelineEvents: LyricLine[] = [
    // { words, time, interval, mode }
    { words: "Forms FORM-29827281-12:", time: 0, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "Test Assessment Report", time: 200, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "\x00\x00\x00\x00\x00\x00\x00", time: 400, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "", time: 710, interval: 0, mode: 'START_MUSIC' },
    { words: "This was a triumph.", time: 730, interval: 2, mode: 'LYRIC_NEWLINE' },
    // We don't need a separate mode for ASCII art, just a different data type
    { words: "I'm making a note here:", time: 1123, interval: 2, mode: 'LYRIC_NEWLINE' },
    { words: "HUGE SUCCESS.", time: 1347, interval: 1.7, mode: 'LYRIC_NEWLINE' },
    { words: "It's hard to overstate", time: 1627, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "my satisfaction.", time: 1873, interval: 2.6, mode: 'LYRIC_NEWLINE' },
    { words: "Aperture Science", time: 2350, interval: 1.8, mode: 'LYRIC_NEWLINE' },
    { words: 0, time: 2350, interval: 0, mode: 'DRAW_ART' }, // ASCII art index 0
    { words: "We do what we must", time: 2733, interval: 1.6, mode: 'LYRIC_NEWLINE' },
    { words: "because we can.", time: 2910, interval: 1.5, mode: 'LYRIC_NEWLINE' },
    { words: "For the good of all of us.", time: 3237, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: 1, time: 3500, interval: 0, mode: 'DRAW_ART' }, // ASCII art index 1
    { words: "Except the ones who are dead.", time: 3567, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "", time: 3717, interval: 0.05, mode: 'LYRIC_NEWLINE' },
    { words: 0, time: 3717, interval: 0, mode: 'DRAW_ART' },
    { words: "But there's no sense crying", time: 3787, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "over every mistake.", time: 3973, interval: 1.77, mode: 'LYRIC_NEWLINE' },
    { words: "You just keep on trying", time: 4170, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "till you run out of cake.", time: 4370, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: 2, time: 4500, interval: 0, mode: 'DRAW_ART' }, // ASCII art index 2
    { words: "And the science gets done.", time: 4570, interval: 1.8, mode: 'LYRIC_NEWLINE' },
    { words: "And you make a neat gun.", time: 4767, interval: 1.7, mode: 'LYRIC_NEWLINE' },
    { words: 0, time: 4903, interval: 0, mode: 'DRAW_ART' }, // ASCII art index 0
    { words: "For the people who are", time: 4973, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "still alive.", time: 5110, interval: 1.6, mode: 'LYRIC_NONEWLINE' },
    { words: 0, time: 5353, interval: 0, mode: 'CLEAR_LYRICS' },
    { words: "Forms FORM-55551-5:", time: 5413, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "Personnel File Addendum:", time: 5477, interval: 1.13, mode: 'LYRIC_NEWLINE' },
    { words: "", time: 5650, interval: 0.05, mode: 'LYRIC_NEWLINE' },
    { words: "Dear <<Subject Name Here>>,", time: 5650, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "", time: 5900, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "I'm not even angry.", time: 5900, interval: 1.86, mode: 'LYRIC_NEWLINE' },
    { words: "I'm being ", time: 6320, interval: -1, mode: 'LYRIC_NONEWLINE' },
    { words: "so ", time: 6413, interval: -1, mode: 'LYRIC_NONEWLINE' },
    { words: "sincere right now.", time: 6470, interval: 1.9, mode: 'LYRIC_NEWLINE' },
    { words: "Even though you broke ", time: 6827, interval: -1, mode: 'LYRIC_NONEWLINE' },
    { words: 3, time: 7020, interval: 0, mode: 'DRAW_ART' },
    { words: "my heart.", time: 7090, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "And killed me.", time: 7170, interval: 1.43, mode: 'LYRIC_NEWLINE' },
    { words: 4, time: 7300, interval: 0, mode: 'DRAW_ART' },
    { words: "And tore me to pieces.", time: 7500, interval: 1.83, mode: 'LYRIC_NEWLINE' },
    { words: "And threw every piece ", time: 7900, interval: -1, mode: 'LYRIC_NONEWLINE' },
    { words: "into a fire.", time: 8080, interval: 1.8, mode: 'LYRIC_NEWLINE' },
    { words: 5, time: 8080, interval: 0, mode: 'DRAW_ART' },
    { words: "As they burned it hurt because", time: 8430, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: 6, time: 8690, interval: 0, mode: 'DRAW_ART' },
    { words: "I was so happy for you!", time: 8760, interval: 1.67, mode: 'LYRIC_NEWLINE' },
    { words: "Now, these points of data", time: 8960, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "make a beautiful line.", time: 9167, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "And we're out of beta.", time: 9357, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "We're releasing on time.", time: 9560, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: 4, time: 9700, interval: 0, mode: 'DRAW_ART' },
    { words: "So I'm GLaD I got burned.", time: 9770, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: 2, time: 9913, interval: 0, mode: 'DRAW_ART' },
    { words: "Think of all the things we learned", time: 9983, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: 0, time: 10120, interval: 0, mode: 'DRAW_ART' },
    { words: "For the people who are", time: 10190, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "Still alive.", time: 10327, interval: 1.8, mode: 'LYRIC_NEWLINE' },
    { words: 0, time: 10603, interval: 0, mode: 'CLEAR_LYRICS' },
    { words: "Forms FORM-55551-6:", time: 10663, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "Personnel File Addendum Addendum:", time: 10710, interval: 1.36, mode: 'LYRIC_NEWLINE' },
    { words: "", time: 10710, interval: 0.05, mode: 'LYRIC_NEWLINE' },
    { words: "One last thing:", time: 10910, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "", time: 11130, interval: 0.05, mode: 'LYRIC_NEWLINE' },
    { words: "Go ahead and leave ", time: 11130, interval: -1, mode: 'LYRIC_NONEWLINE' },
    { words: "me.", time: 11280, interval: 0.5, mode: 'LYRIC_NEWLINE' },
    { words: "I think I'd prefer to stay ", time: 11507, interval: -1, mode: 'LYRIC_NONEWLINE' },
    { words: "inside.", time: 11787, interval: 1.13, mode: 'LYRIC_NEWLINE' },
    { words: "Maybe you'll find someone else", time: 12037, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "To help you.", time: 12390, interval: 1.23, mode: 'LYRIC_NEWLINE' },
    { words: "Maybe Black ", time: 12737, interval: -1, mode: 'LYRIC_NONEWLINE' },
    { words: 7, time: 12787, interval: 0, mode: 'DRAW_ART' },
    { words: "Mesa...", time: 12857, interval: 2.7, mode: 'LYRIC_NEWLINE' },
    { words: "THAT WAS A JOKE.", time: 13137, interval: 1.46, mode: 'LYRIC_NONEWLINE' },
    { words: " FAT CHANCE.", time: 13387, interval: 1.1, mode: 'LYRIC_NEWLINE' },
    { words: "Anyway, ", time: 13620, interval: -1, mode: 'LYRIC_NONEWLINE' },
    { words: 8, time: 13670, interval: 0, mode: 'DRAW_ART' },
    { words: "this cake is great.", time: 13740, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "It's so delicious and moist.", time: 13963, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: 9, time: 14123, interval: 0, mode: 'DRAW_ART' },
    { words: "Look at me still talking", time: 14193, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: 1, time: 14320, interval: 0, mode: 'DRAW_ART' },
    { words: "when there's science to do.", time: 14390, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: 0, time: 14527, interval: 0, mode: 'DRAW_ART' },
    { words: "When I look out there,", time: 14597, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "It makes me GLaD I'm not you.", time: 14767, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: 2, time: 14913, interval: 0, mode: 'DRAW_ART' },
    { words: "I've experiments to run.", time: 14983, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: 4, time: 15120, interval: 0, mode: 'DRAW_ART' },
    { words: "There is research to be done.", time: 15190, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: 0, time: 15320, interval: 0, mode: 'DRAW_ART' },
    { words: "On the people who are", time: 15390, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "still alive", time: 15553, interval: 2.0, mode: 'LYRIC_NONEWLINE' },
    { words: 0, time: 15697, interval: 0, mode: 'CLEAR_LYRICS' },
    { words: "", time: 15757, interval: 0.05, mode: 'LYRIC_NEWLINE' },
    { words: "", time: 15757, interval: 0.05, mode: 'LYRIC_NEWLINE' },
    { words: "", time: 15757, interval: 0.05, mode: 'LYRIC_NEWLINE' },
    { words: "PS: And believe me I am", time: 15757, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "still alive.", time: 15960, interval: 1.13, mode: 'LYRIC_NEWLINE' },
    { words: "PPS: I'm doing Science and I'm", time: 16150, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "still alive.", time: 16363, interval: 1.13, mode: 'LYRIC_NEWLINE' },
    { words: "PPPS: I feel FANTASTIC and I'm", time: 16550, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "still alive.", time: 16760, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "", time: 16860, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "FINAL THOUGHT:", time: 16860, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "While you're dying I'll be", time: 16993, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "still alive.", time: 17157, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "", time: 17277, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "FINAL THOUGHT PS:", time: 17277, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "And when you're dead I will be", time: 17367, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "still alive.", time: 17550, interval: 1.13, mode: 'LYRIC_NEWLINE' },
    { words: "", time: 17550, interval: -1, mode: 'LYRIC_NEWLINE' },
    { words: "", time: 17550, interval: 0.05, mode: 'LYRIC_NEWLINE' },
    { words: "STILL ALIVE", time: 17760, interval: 1.13, mode: 'LYRIC_NEWLINE' },
    { words: 0, time: 17900, interval: 0, mode: 'CLEAR_LYRICS' },
    { words: 0, time: 18500, interval: 0, mode: 'CLEAR_LYRICS' },
    { words: "ENDENDENDENDENDENDENDEND", time: 18500, interval: 0.05, mode: 'END' },

];